name: Gradle

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Build with Gradle
      run: ./gradlew
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        path: build/libs/NFServer*-all.jar
